#!/bin/bash

max=$((120 - 1))
batch=500

img_header=16
img_file="train-images-idx3-ubyte"
time for x in $(seq 0 $max); do
    num=$(printf "%03d" $x)
    unit=$((28 * 28 * batch))
    dd if=$img_file of=t/$img_file-$num.bmp bs=1 count=$unit skip=$((img_header + x * unit))
done

lvl_header=8
lvl_file="train-labels-idx1-ubyte"
for x in $(seq 0 $max); do
    num=$(printf "%03d" $x)
    unit=$((1 * batch))
    dd if=$lvl_file of=t/$lvl_file-$num.lvl bs=1 count=$unit skip=$((lvl_header + x * unit))
done

